### ISSUE TITLE
denoise_credible.py

### ISSUE THREAD

**Issue by minmini2** [yuleung/MixBCT#1]
Hello, I am interested in your wonderful work. 
While following your command "Step-2 ----（preprocessing operations）used in MixBCT" ,
denoise_credible.py doesn't work.
if variable count_pre and count_last are set to zero, there must be error. Can you check your code?
or is there any guide to set them? 
Thank you for your reading.

**Comment by yuleung** [comment]
Hello, I‘sorry for the delayed response! I didn't notice the issue until recently.

I compared my original code and it seems that the code is fine, the count_pre and the count_last are used to identify the boundaries of all samples belonging to the same class.  

Note that when performing the denoising operation, it's necessary to ensure that the labels of the data are contiguous, meaning that samples from the same category are grouped together. For example: 111222333333....
